language: generic
dist: xenial
sudo: required

before_install:
  - source scripts/install-cuda.sh

install:
  - nvcc --version

script:
  - source tests/gate.sh

notifications:
  slack:
    on_success: always
    on_failure: always
